apiVersion: v1
kind: ConfigMap
metadata:
  name: javas-configmap
data:
  product_url: product-service-sv
  price_url: price-service-sv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-depl
  labels:
    app: web-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-depl
  template:
    metadata:
      labels:
        app: web-depl
    spec:
      containers:
        - name: web-depl
          image: kimlongap/dockertest01:spring-petclinic
          #restartPolicy: Never
          #imagePullPolicy: "Always"
          env:
            - name: MYSQL_URL
              value: jdbc:mysql://db-service/petclinic    
            - name: MYSQL_USER
              value: petclinic222
          ports:
            - containerPort: 8220                                 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-depl
  labels:
    app: db-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-depl
  template:
    metadata:
      labels:
        app: db-depl
    spec:
      containers:
        - name: db-depl
          image: mysql:5.7
          env:         
            - name: MYSQL_ROOT_PASSWORD
              value: 'a'
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: 'true'
            - name: MYSQL_USER
              value: 'petclinic222'
            - name: MYSQL_PASSWORD
              value: 'petclinic'
            - name: MYSQL_DATABASE
              value: 'petclinic'                                                      
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web-depl
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8220
      targetPort: 8220
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db-depl
  type: NodePort    
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

